trigger:
  branches:
    include:
      - main

jobs:
  - job: BuildJobLinux
    displayName: 'Build C++ Project (Linux)'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - task: CMake@1
        displayName: 'Configure CMake (Linux)'
        inputs:
          cmakeArgs: '-B build -DCMAKE_BUILD_TYPE=Release'
          workingDirectory: '$(Build.SourcesDirectory)'

      - task: CMake@1
        displayName: 'Build C++ Project (Linux)'
        inputs:
          cmakeArgs: '--build .'
          workingDirectory: '$(Build.SourcesDirectory)/build'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.SourcesDirectory)/build'
          artifact: 'Build-Linux'
          publishLocation: 'pipeline'

  - job: BuildJobWindows
    displayName: 'Build C++ Project (Windows)'
    pool:
      vmImage: 'windows-latest'
    steps:
      - checkout: self

      - task: CMake@1
        displayName: 'Configure CMake (Windows)'
        inputs:
          cmakeArgs: '-B build -DCMAKE_BUILD_TYPE=Release'
          workingDirectory: '$(Build.SourcesDirectory)'

      - task: CMake@1
        displayName: 'Build C++ Project (Windows)'
        inputs:
          cmakeArgs: '--build .'
          workingDirectory: '$(Build.SourcesDirectory)/build'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.SourcesDirectory)/build'
          artifact: 'Build-Windows'
          publishLocation: 'pipeline'
