var searchData=
[
  ['imbitarray_0',['ImBitArray',['../structImBitArray.html',1,'']]],
  ['imbitarray_3c_20imguikey_5fnamedkey_5fcount_2c_20_2dimguikey_5fnamedkey_5fbegin_20_3e_1',['ImBitArray&lt; ImGuiKey_NamedKey_COUNT, -ImGuiKey_NamedKey_BEGIN &gt;',['../structImBitArray.html',1,'']]],
  ['imbitvector_2',['ImBitVector',['../structImBitVector.html',1,'']]],
  ['imchunkstream_3',['ImChunkStream',['../structImChunkStream.html',1,'']]],
  ['imchunkstream_3c_20imguitablesettings_20_3e_4',['ImChunkStream&lt; ImGuiTableSettings &gt;',['../structImChunkStream.html',1,'']]],
  ['imchunkstream_3c_20imguiwindowsettings_20_3e_5',['ImChunkStream&lt; ImGuiWindowSettings &gt;',['../structImChunkStream.html',1,'']]],
  ['imcolor_6',['ImColor',['../structImColor.html',1,'']]],
  ['imdrawchannel_7',['ImDrawChannel',['../structImDrawChannel.html',1,'']]],
  ['imdrawcmd_8',['ImDrawCmd',['../structImDrawCmd.html',1,'']]],
  ['imdrawcmdheader_9',['ImDrawCmdHeader',['../structImDrawCmdHeader.html',1,'']]],
  ['imdrawdata_10',['ImDrawData',['../structImDrawData.html',1,'']]],
  ['imdrawdatabuilder_11',['ImDrawDataBuilder',['../structImDrawDataBuilder.html',1,'']]],
  ['imdrawlist_12',['ImDrawList',['../structImDrawList.html',1,'']]],
  ['imdrawlistshareddata_13',['ImDrawListSharedData',['../structImDrawListSharedData.html',1,'']]],
  ['imdrawlistsplitter_14',['ImDrawListSplitter',['../structImDrawListSplitter.html',1,'']]],
  ['imdrawvert_15',['ImDrawVert',['../structImDrawVert.html',1,'']]],
  ['imdrawvertallegro_16',['ImDrawVertAllegro',['../structImDrawVertAllegro.html',1,'']]],
  ['imfont_17',['ImFont',['../structImFont.html',1,'']]],
  ['imfontatlas_18',['ImFontAtlas',['../structImFontAtlas.html',1,'']]],
  ['imfontatlascustomrect_19',['ImFontAtlasCustomRect',['../structImFontAtlasCustomRect.html',1,'']]],
  ['imfontbuilddstdata_20',['ImFontBuildDstData',['../structImFontBuildDstData.html',1,'']]],
  ['imfontbuilddstdataft_21',['ImFontBuildDstDataFT',['../structImFontBuildDstDataFT.html',1,'']]],
  ['imfontbuilderio_22',['ImFontBuilderIO',['../structImFontBuilderIO.html',1,'']]],
  ['imfontbuildsrcdata_23',['ImFontBuildSrcData',['../structImFontBuildSrcData.html',1,'']]],
  ['imfontbuildsrcdataft_24',['ImFontBuildSrcDataFT',['../structImFontBuildSrcDataFT.html',1,'']]],
  ['imfontbuildsrcglyphft_25',['ImFontBuildSrcGlyphFT',['../structImFontBuildSrcGlyphFT.html',1,'']]],
  ['imfontconfig_26',['ImFontConfig',['../structImFontConfig.html',1,'']]],
  ['imfontglyph_27',['ImFontGlyph',['../structImFontGlyph.html',1,'']]],
  ['imfontglyphrangesbuilder_28',['ImFontGlyphRangesBuilder',['../structImFontGlyphRangesBuilder.html',1,'']]],
  ['imgl3wprocs_29',['ImGL3WProcs',['../unionImGL3WProcs.html',1,'']]],
  ['imgui_5fimplallegro5_5fdata_30',['ImGui_ImplAllegro5_Data',['../structImGui__ImplAllegro5__Data.html',1,'']]],
  ['imgui_5fimpldx10_5fdata_31',['ImGui_ImplDX10_Data',['../structImGui__ImplDX10__Data.html',1,'']]],
  ['imgui_5fimpldx10_5fviewportdata_32',['ImGui_ImplDX10_ViewportData',['../structImGui__ImplDX10__ViewportData.html',1,'']]],
  ['imgui_5fimpldx11_5fdata_33',['ImGui_ImplDX11_Data',['../structImGui__ImplDX11__Data.html',1,'']]],
  ['imgui_5fimpldx11_5fviewportdata_34',['ImGui_ImplDX11_ViewportData',['../structImGui__ImplDX11__ViewportData.html',1,'']]],
  ['imgui_5fimpldx12_5fdata_35',['ImGui_ImplDX12_Data',['../structImGui__ImplDX12__Data.html',1,'']]],
  ['imgui_5fimpldx12_5fframecontext_36',['ImGui_ImplDX12_FrameContext',['../structImGui__ImplDX12__FrameContext.html',1,'']]],
  ['imgui_5fimpldx12_5frenderbuffers_37',['ImGui_ImplDX12_RenderBuffers',['../structImGui__ImplDX12__RenderBuffers.html',1,'']]],
  ['imgui_5fimpldx12_5fviewportdata_38',['ImGui_ImplDX12_ViewportData',['../structImGui__ImplDX12__ViewportData.html',1,'']]],
  ['imgui_5fimpldx9_5fdata_39',['ImGui_ImplDX9_Data',['../structImGui__ImplDX9__Data.html',1,'']]],
  ['imgui_5fimpldx9_5fviewportdata_40',['ImGui_ImplDX9_ViewportData',['../structImGui__ImplDX9__ViewportData.html',1,'']]],
  ['imgui_5fimplmetal_5fdata_41',['ImGui_ImplMetal_Data',['../structImGui__ImplMetal__Data.html',1,'']]],
  ['imgui_5fimplopengl2_5fdata_42',['ImGui_ImplOpenGL2_Data',['../structImGui__ImplOpenGL2__Data.html',1,'']]],
  ['imgui_5fimplopengl3_5fdata_43',['ImGui_ImplOpenGL3_Data',['../structImGui__ImplOpenGL3__Data.html',1,'']]],
  ['imgui_5fimplosx_5fdata_44',['ImGui_ImplOSX_Data',['../structImGui__ImplOSX__Data.html',1,'']]],
  ['imgui_5fimplosx_5fwindow_45',['ImGui_ImplOSX_Window',['../interfaceImGui__ImplOSX__Window.html',1,'']]],
  ['imgui_5fimplsdl2_5fdata_46',['ImGui_ImplSDL2_Data',['../structImGui__ImplSDL2__Data.html',1,'']]],
  ['imgui_5fimplsdl2_5fviewportdata_47',['ImGui_ImplSDL2_ViewportData',['../structImGui__ImplSDL2__ViewportData.html',1,'']]],
  ['imgui_5fimplsdl3_5fdata_48',['ImGui_ImplSDL3_Data',['../structImGui__ImplSDL3__Data.html',1,'']]],
  ['imgui_5fimplsdl3_5fviewportdata_49',['ImGui_ImplSDL3_ViewportData',['../structImGui__ImplSDL3__ViewportData.html',1,'']]],
  ['imgui_5fimplsdlrenderer2_5fdata_50',['ImGui_ImplSDLRenderer2_Data',['../structImGui__ImplSDLRenderer2__Data.html',1,'']]],
  ['imgui_5fimplsdlrenderer3_5fdata_51',['ImGui_ImplSDLRenderer3_Data',['../structImGui__ImplSDLRenderer3__Data.html',1,'']]],
  ['imgui_5fimplvulkan_5fdata_52',['ImGui_ImplVulkan_Data',['../structImGui__ImplVulkan__Data.html',1,'']]],
  ['imgui_5fimplvulkan_5fframerenderbuffers_53',['ImGui_ImplVulkan_FrameRenderBuffers',['../structImGui__ImplVulkan__FrameRenderBuffers.html',1,'']]],
  ['imgui_5fimplvulkan_5finitinfo_54',['ImGui_ImplVulkan_InitInfo',['../structImGui__ImplVulkan__InitInfo.html',1,'']]],
  ['imgui_5fimplvulkan_5fviewportdata_55',['ImGui_ImplVulkan_ViewportData',['../structImGui__ImplVulkan__ViewportData.html',1,'']]],
  ['imgui_5fimplvulkan_5fwindowrenderbuffers_56',['ImGui_ImplVulkan_WindowRenderBuffers',['../structImGui__ImplVulkan__WindowRenderBuffers.html',1,'']]],
  ['imgui_5fimplvulkanh_5fframe_57',['ImGui_ImplVulkanH_Frame',['../structImGui__ImplVulkanH__Frame.html',1,'']]],
  ['imgui_5fimplvulkanh_5fframesemaphores_58',['ImGui_ImplVulkanH_FrameSemaphores',['../structImGui__ImplVulkanH__FrameSemaphores.html',1,'']]],
  ['imgui_5fimplvulkanh_5fwindow_59',['ImGui_ImplVulkanH_Window',['../structImGui__ImplVulkanH__Window.html',1,'']]],
  ['imgui_5fimplwgpu_5fdata_60',['ImGui_ImplWGPU_Data',['../structImGui__ImplWGPU__Data.html',1,'']]],
  ['imgui_5fimplwgpu_5finitinfo_61',['ImGui_ImplWGPU_InitInfo',['../structImGui__ImplWGPU__InitInfo.html',1,'']]],
  ['imgui_5fimplwin32_5fdata_62',['ImGui_ImplWin32_Data',['../structImGui__ImplWin32__Data.html',1,'']]],
  ['imgui_5fimplwin32_5fviewportdata_63',['ImGui_ImplWin32_ViewportData',['../structImGui__ImplWin32__ViewportData.html',1,'']]],
  ['imguiboxselectstate_64',['ImGuiBoxSelectState',['../structImGuiBoxSelectState.html',1,'']]],
  ['imguicolormod_65',['ImGuiColorMod',['../structImGuiColorMod.html',1,'']]],
  ['imguicombopreviewdata_66',['ImGuiComboPreviewData',['../structImGuiComboPreviewData.html',1,'']]],
  ['imguicontext_67',['ImGuiContext',['../structImGuiContext.html',1,'']]],
  ['imguicontexthook_68',['ImGuiContextHook',['../structImGuiContextHook.html',1,'']]],
  ['imguidatatypeinfo_69',['ImGuiDataTypeInfo',['../structImGuiDataTypeInfo.html',1,'']]],
  ['imguidatatypestorage_70',['ImGuiDataTypeStorage',['../structImGuiDataTypeStorage.html',1,'']]],
  ['imguidatavarinfo_71',['ImGuiDataVarInfo',['../structImGuiDataVarInfo.html',1,'']]],
  ['imguidebugallocentry_72',['ImGuiDebugAllocEntry',['../structImGuiDebugAllocEntry.html',1,'']]],
  ['imguidebugallocinfo_73',['ImGuiDebugAllocInfo',['../structImGuiDebugAllocInfo.html',1,'']]],
  ['imguidockcontext_74',['ImGuiDockContext',['../structImGuiDockContext.html',1,'']]],
  ['imguidockcontextprunenodedata_75',['ImGuiDockContextPruneNodeData',['../structImGuiDockContextPruneNodeData.html',1,'']]],
  ['imguidocknode_76',['ImGuiDockNode',['../structImGuiDockNode.html',1,'']]],
  ['imguidocknodesettings_77',['ImGuiDockNodeSettings',['../structImGuiDockNodeSettings.html',1,'']]],
  ['imguidocknodetreeinfo_78',['ImGuiDockNodeTreeInfo',['../structImGuiDockNodeTreeInfo.html',1,'']]],
  ['imguidockpreviewdata_79',['ImGuiDockPreviewData',['../structImGuiDockPreviewData.html',1,'']]],
  ['imguidockrequest_80',['ImGuiDockRequest',['../structImGuiDockRequest.html',1,'']]],
  ['imguifocusscopedata_81',['ImGuiFocusScopeData',['../structImGuiFocusScopeData.html',1,'']]],
  ['imguigetnamefromindexoldtonewcallbackdata_82',['ImGuiGetNameFromIndexOldToNewCallbackData',['../structImGuiGetNameFromIndexOldToNewCallbackData.html',1,'']]],
  ['imguigroupdata_83',['ImGuiGroupData',['../structImGuiGroupData.html',1,'']]],
  ['imguiidstacktool_84',['ImGuiIDStackTool',['../structImGuiIDStackTool.html',1,'']]],
  ['imguiinputevent_85',['ImGuiInputEvent',['../structImGuiInputEvent.html',1,'']]],
  ['imguiinputeventappfocused_86',['ImGuiInputEventAppFocused',['../structImGuiInputEventAppFocused.html',1,'']]],
  ['imguiinputeventkey_87',['ImGuiInputEventKey',['../structImGuiInputEventKey.html',1,'']]],
  ['imguiinputeventmousebutton_88',['ImGuiInputEventMouseButton',['../structImGuiInputEventMouseButton.html',1,'']]],
  ['imguiinputeventmousepos_89',['ImGuiInputEventMousePos',['../structImGuiInputEventMousePos.html',1,'']]],
  ['imguiinputeventmouseviewport_90',['ImGuiInputEventMouseViewport',['../structImGuiInputEventMouseViewport.html',1,'']]],
  ['imguiinputeventmousewheel_91',['ImGuiInputEventMouseWheel',['../structImGuiInputEventMouseWheel.html',1,'']]],
  ['imguiinputeventtext_92',['ImGuiInputEventText',['../structImGuiInputEventText.html',1,'']]],
  ['imguiinputtextcallbackdata_93',['ImGuiInputTextCallbackData',['../structImGuiInputTextCallbackData.html',1,'']]],
  ['imguiinputtextdeactivatedstate_94',['ImGuiInputTextDeactivatedState',['../structImGuiInputTextDeactivatedState.html',1,'']]],
  ['imguiinputtextstate_95',['ImGuiInputTextState',['../structImGuiInputTextState.html',1,'']]],
  ['imguiio_96',['ImGuiIO',['../structImGuiIO.html',1,'']]],
  ['imguikeydata_97',['ImGuiKeyData',['../structImGuiKeyData.html',1,'']]],
  ['imguikeyownerdata_98',['ImGuiKeyOwnerData',['../structImGuiKeyOwnerData.html',1,'']]],
  ['imguikeyroutingdata_99',['ImGuiKeyRoutingData',['../structImGuiKeyRoutingData.html',1,'']]],
  ['imguikeyroutingtable_100',['ImGuiKeyRoutingTable',['../structImGuiKeyRoutingTable.html',1,'']]],
  ['imguilastitemdata_101',['ImGuiLastItemData',['../structImGuiLastItemData.html',1,'']]],
  ['imguilistclipper_102',['ImGuiListClipper',['../structImGuiListClipper.html',1,'']]],
  ['imguilistclipperdata_103',['ImGuiListClipperData',['../structImGuiListClipperData.html',1,'']]],
  ['imguilistclipperrange_104',['ImGuiListClipperRange',['../structImGuiListClipperRange.html',1,'']]],
  ['imguilocentry_105',['ImGuiLocEntry',['../structImGuiLocEntry.html',1,'']]],
  ['imguimenucolumns_106',['ImGuiMenuColumns',['../structImGuiMenuColumns.html',1,'']]],
  ['imguimetricsconfig_107',['ImGuiMetricsConfig',['../structImGuiMetricsConfig.html',1,'']]],
  ['imguimultiselectio_108',['ImGuiMultiSelectIO',['../structImGuiMultiSelectIO.html',1,'']]],
  ['imguimultiselectstate_109',['ImGuiMultiSelectState',['../structImGuiMultiSelectState.html',1,'']]],
  ['imguimultiselecttempdata_110',['ImGuiMultiSelectTempData',['../structImGuiMultiSelectTempData.html',1,'']]],
  ['imguinavitemdata_111',['ImGuiNavItemData',['../structImGuiNavItemData.html',1,'']]],
  ['imguinextitemdata_112',['ImGuiNextItemData',['../structImGuiNextItemData.html',1,'']]],
  ['imguinextwindowdata_113',['ImGuiNextWindowData',['../structImGuiNextWindowData.html',1,'']]],
  ['imguiobserver_114',['ImGuiObserver',['../interfaceImGuiObserver.html',1,'']]],
  ['imguioldcolumndata_115',['ImGuiOldColumnData',['../structImGuiOldColumnData.html',1,'']]],
  ['imguioldcolumns_116',['ImGuiOldColumns',['../structImGuiOldColumns.html',1,'']]],
  ['imguionceuponaframe_117',['ImGuiOnceUponAFrame',['../structImGuiOnceUponAFrame.html',1,'']]],
  ['imguipayload_118',['ImGuiPayload',['../structImGuiPayload.html',1,'']]],
  ['imguiplatformimedata_119',['ImGuiPlatformImeData',['../structImGuiPlatformImeData.html',1,'']]],
  ['imguiplatformio_120',['ImGuiPlatformIO',['../structImGuiPlatformIO.html',1,'']]],
  ['imguiplatformmonitor_121',['ImGuiPlatformMonitor',['../structImGuiPlatformMonitor.html',1,'']]],
  ['imguiplotarraygetterdata_122',['ImGuiPlotArrayGetterData',['../structImGuiPlotArrayGetterData.html',1,'']]],
  ['imguipopupdata_123',['ImGuiPopupData',['../structImGuiPopupData.html',1,'']]],
  ['imguiptrorindex_124',['ImGuiPtrOrIndex',['../structImGuiPtrOrIndex.html',1,'']]],
  ['imguiresizeborderdef_125',['ImGuiResizeBorderDef',['../structImGuiResizeBorderDef.html',1,'']]],
  ['imguiresizegripdef_126',['ImGuiResizeGripDef',['../structImGuiResizeGripDef.html',1,'']]],
  ['imguiselectionbasicstorage_127',['ImGuiSelectionBasicStorage',['../structImGuiSelectionBasicStorage.html',1,'']]],
  ['imguiselectionexternalstorage_128',['ImGuiSelectionExternalStorage',['../structImGuiSelectionExternalStorage.html',1,'']]],
  ['imguiselectionrequest_129',['ImGuiSelectionRequest',['../structImGuiSelectionRequest.html',1,'']]],
  ['imguisettingshandler_130',['ImGuiSettingsHandler',['../structImGuiSettingsHandler.html',1,'']]],
  ['imguishrinkwidthitem_131',['ImGuiShrinkWidthItem',['../structImGuiShrinkWidthItem.html',1,'']]],
  ['imguisizecallbackdata_132',['ImGuiSizeCallbackData',['../structImGuiSizeCallbackData.html',1,'']]],
  ['imguistacklevelinfo_133',['ImGuiStackLevelInfo',['../structImGuiStackLevelInfo.html',1,'']]],
  ['imguistacksizes_134',['ImGuiStackSizes',['../structImGuiStackSizes.html',1,'']]],
  ['imguistorage_135',['ImGuiStorage',['../structImGuiStorage.html',1,'']]],
  ['imguistoragepair_136',['ImGuiStoragePair',['../structImGuiStoragePair.html',1,'']]],
  ['imguistyle_137',['ImGuiStyle',['../structImGuiStyle.html',1,'']]],
  ['imguistylemod_138',['ImGuiStyleMod',['../structImGuiStyleMod.html',1,'']]],
  ['imguitabbar_139',['ImGuiTabBar',['../structImGuiTabBar.html',1,'']]],
  ['imguitabbarsection_140',['ImGuiTabBarSection',['../structImGuiTabBarSection.html',1,'']]],
  ['imguitabitem_141',['ImGuiTabItem',['../structImGuiTabItem.html',1,'']]],
  ['imguitable_142',['ImGuiTable',['../structImGuiTable.html',1,'']]],
  ['imguitablecelldata_143',['ImGuiTableCellData',['../structImGuiTableCellData.html',1,'']]],
  ['imguitablecolumn_144',['ImGuiTableColumn',['../structImGuiTableColumn.html',1,'']]],
  ['imguitablecolumnsettings_145',['ImGuiTableColumnSettings',['../structImGuiTableColumnSettings.html',1,'']]],
  ['imguitablecolumnsortspecs_146',['ImGuiTableColumnSortSpecs',['../structImGuiTableColumnSortSpecs.html',1,'']]],
  ['imguitableheaderdata_147',['ImGuiTableHeaderData',['../structImGuiTableHeaderData.html',1,'']]],
  ['imguitableinstancedata_148',['ImGuiTableInstanceData',['../structImGuiTableInstanceData.html',1,'']]],
  ['imguitablesettings_149',['ImGuiTableSettings',['../structImGuiTableSettings.html',1,'']]],
  ['imguitablesortspecs_150',['ImGuiTableSortSpecs',['../structImGuiTableSortSpecs.html',1,'']]],
  ['imguitabletempdata_151',['ImGuiTableTempData',['../structImGuiTableTempData.html',1,'']]],
  ['imguitextbuffer_152',['ImGuiTextBuffer',['../structImGuiTextBuffer.html',1,'']]],
  ['imguitextfilter_153',['ImGuiTextFilter',['../structImGuiTextFilter.html',1,'']]],
  ['imguitextindex_154',['ImGuiTextIndex',['../structImGuiTextIndex.html',1,'']]],
  ['imguitextrange_155',['ImGuiTextRange',['../structImGuiTextFilter_1_1ImGuiTextRange.html',1,'ImGuiTextFilter']]],
  ['imguitreenodestackdata_156',['ImGuiTreeNodeStackData',['../structImGuiTreeNodeStackData.html',1,'']]],
  ['imguitypingselectrequest_157',['ImGuiTypingSelectRequest',['../structImGuiTypingSelectRequest.html',1,'']]],
  ['imguitypingselectstate_158',['ImGuiTypingSelectState',['../structImGuiTypingSelectState.html',1,'']]],
  ['imguiviewport_159',['ImGuiViewport',['../structImGuiViewport.html',1,'']]],
  ['imguiviewportdatametal_160',['ImGuiViewportDataMetal',['../structImGuiViewportDataMetal.html',1,'']]],
  ['imguiviewportdataosx_161',['ImGuiViewportDataOSX',['../structImGuiViewportDataOSX.html',1,'']]],
  ['imguiviewportp_162',['ImGuiViewportP',['../structImGuiViewportP.html',1,'']]],
  ['imguiwindow_163',['ImGuiWindow',['../structImGuiWindow.html',1,'']]],
  ['imguiwindowclass_164',['ImGuiWindowClass',['../structImGuiWindowClass.html',1,'']]],
  ['imguiwindowdockstyle_165',['ImGuiWindowDockStyle',['../structImGuiWindowDockStyle.html',1,'']]],
  ['imguiwindowsettings_166',['ImGuiWindowSettings',['../structImGuiWindowSettings.html',1,'']]],
  ['imguiwindowstackdata_167',['ImGuiWindowStackData',['../structImGuiWindowStackData.html',1,'']]],
  ['imguiwindowtempdata_168',['ImGuiWindowTempData',['../structImGuiWindowTempData.html',1,'']]],
  ['imnewwrapper_169',['ImNewWrapper',['../structImNewWrapper.html',1,'']]],
  ['impool_170',['ImPool',['../structImPool.html',1,'']]],
  ['impool_3c_20imguimultiselectstate_20_3e_171',['ImPool&lt; ImGuiMultiSelectState &gt;',['../structImPool.html',1,'']]],
  ['impool_3c_20imguitabbar_20_3e_172',['ImPool&lt; ImGuiTabBar &gt;',['../structImPool.html',1,'']]],
  ['impool_3c_20imguitable_20_3e_173',['ImPool&lt; ImGuiTable &gt;',['../structImPool.html',1,'']]],
  ['imrect_174',['ImRect',['../structImRect.html',1,'']]],
  ['imspan_175',['ImSpan',['../structImSpan.html',1,'']]],
  ['imspan_3c_20imguitablecelldata_20_3e_176',['ImSpan&lt; ImGuiTableCellData &gt;',['../structImSpan.html',1,'']]],
  ['imspan_3c_20imguitablecolumn_20_3e_177',['ImSpan&lt; ImGuiTableColumn &gt;',['../structImSpan.html',1,'']]],
  ['imspan_3c_20imguitablecolumnidx_20_3e_178',['ImSpan&lt; ImGuiTableColumnIdx &gt;',['../structImSpan.html',1,'']]],
  ['imspanallocator_179',['ImSpanAllocator',['../structImSpanAllocator.html',1,'']]],
  ['imtriangulator_180',['ImTriangulator',['../structImTriangulator.html',1,'']]],
  ['imtriangulatornode_181',['ImTriangulatorNode',['../structImTriangulatorNode.html',1,'']]],
  ['imtriangulatornodespan_182',['ImTriangulatorNodeSpan',['../structImTriangulatorNodeSpan.html',1,'']]],
  ['imvec1_183',['ImVec1',['../structImVec1.html',1,'']]],
  ['imvec2_184',['ImVec2',['../structImVec2.html',1,'']]],
  ['imvec2ih_185',['ImVec2ih',['../structImVec2ih.html',1,'']]],
  ['imvec4_186',['ImVec4',['../structImVec4.html',1,'']]],
  ['imvector_187',['ImVector',['../structImVector.html',1,'']]],
  ['imvector_3c_20char_20_2a_20_3e_188',['ImVector&lt; char * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20char_20_3e_189',['ImVector&lt; char &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20const_20char_20_2a_20_3e_190',['ImVector&lt; const char * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20exampleasset_20_3e_191',['ImVector&lt; ExampleAsset &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20exampletreenode_20_2a_20_3e_192',['ImVector&lt; ExampleTreeNode * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20float_20_3e_193',['ImVector&lt; float &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imdrawchannel_20_3e_194',['ImVector&lt; ImDrawChannel &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imdrawcmd_20_3e_195',['ImVector&lt; ImDrawCmd &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imdrawidx_20_3e_196',['ImVector&lt; ImDrawIdx &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imdrawlist_20_2a_20_3e_197',['ImVector&lt; ImDrawList * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imdrawvert_20_3e_198',['ImVector&lt; ImDrawVert &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imdrawvertallegro_20_3e_199',['ImVector&lt; ImDrawVertAllegro &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imfont_20_2a_20_3e_200',['ImVector&lt; ImFont * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imfontatlascustomrect_20_3e_201',['ImVector&lt; ImFontAtlasCustomRect &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imfontbuildsrcglyphft_20_3e_202',['ImVector&lt; ImFontBuildSrcGlyphFT &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imfontconfig_20_3e_203',['ImVector&lt; ImFontConfig &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imfontglyph_20_3e_204',['ImVector&lt; ImFontGlyph &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguicolormod_20_3e_205',['ImVector&lt; ImGuiColorMod &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguicontexthook_20_3e_206',['ImVector&lt; ImGuiContextHook &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguidocknodesettings_20_3e_207',['ImVector&lt; ImGuiDockNodeSettings &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguidockrequest_20_3e_208',['ImVector&lt; ImGuiDockRequest &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguifocusscopedata_20_3e_209',['ImVector&lt; ImGuiFocusScopeData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguigroupdata_20_3e_210',['ImVector&lt; ImGuiGroupData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiid_20_3e_211',['ImVector&lt; ImGuiID &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiinputevent_20_3e_212',['ImVector&lt; ImGuiInputEvent &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiitemflags_20_3e_213',['ImVector&lt; ImGuiItemFlags &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguikeyroutingdata_20_3e_214',['ImVector&lt; ImGuiKeyRoutingData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguilistclipperdata_20_3e_215',['ImVector&lt; ImGuiListClipperData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguilistclipperrange_20_3e_216',['ImVector&lt; ImGuiListClipperRange &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguimultiselectstate_20_3e_217',['ImVector&lt; ImGuiMultiSelectState &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguimultiselecttempdata_20_3e_218',['ImVector&lt; ImGuiMultiSelectTempData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguioldcolumndata_20_3e_219',['ImVector&lt; ImGuiOldColumnData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguioldcolumns_20_3e_220',['ImVector&lt; ImGuiOldColumns &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiplatformmonitor_20_3e_221',['ImVector&lt; ImGuiPlatformMonitor &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguipopupdata_20_3e_222',['ImVector&lt; ImGuiPopupData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiptrorindex_20_3e_223',['ImVector&lt; ImGuiPtrOrIndex &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiselectionrequest_20_3e_224',['ImVector&lt; ImGuiSelectionRequest &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguisettingshandler_20_3e_225',['ImVector&lt; ImGuiSettingsHandler &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguishrinkwidthitem_20_3e_226',['ImVector&lt; ImGuiShrinkWidthItem &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguistacklevelinfo_20_3e_227',['ImVector&lt; ImGuiStackLevelInfo &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguistoragepair_20_3e_228',['ImVector&lt; ImGuiStoragePair &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguistylemod_20_3e_229',['ImVector&lt; ImGuiStyleMod &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitabbar_20_3e_230',['ImVector&lt; ImGuiTabBar &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitabitem_20_3e_231',['ImVector&lt; ImGuiTabItem &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitable_20_3e_232',['ImVector&lt; ImGuiTable &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitablecolumnsortspecs_20_3e_233',['ImVector&lt; ImGuiTableColumnSortSpecs &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitableheaderdata_20_3e_234',['ImVector&lt; ImGuiTableHeaderData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitableinstancedata_20_3e_235',['ImVector&lt; ImGuiTableInstanceData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitabletempdata_20_3e_236',['ImVector&lt; ImGuiTableTempData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitextfilter_3a_3aimguitextrange_20_3e_237',['ImVector&lt; ImGuiTextFilter::ImGuiTextRange &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitreenodestackdata_20_3e_238',['ImVector&lt; ImGuiTreeNodeStackData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiviewport_20_2a_20_3e_239',['ImVector&lt; ImGuiViewport * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiviewportp_20_2a_20_3e_240',['ImVector&lt; ImGuiViewportP * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiwindow_20_2a_20_3e_241',['ImVector&lt; ImGuiWindow * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiwindowstackdata_20_3e_242',['ImVector&lt; ImGuiWindowStackData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imtextureid_20_3e_243',['ImVector&lt; ImTextureID &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imu32_20_3e_244',['ImVector&lt; ImU32 &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imvec2_20_3e_245',['ImVector&lt; ImVec2 &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imvec4_20_3e_246',['ImVector&lt; ImVec4 &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imwchar_20_3e_247',['ImVector&lt; ImWchar &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20int_20_3e_248',['ImVector&lt; int &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20mydocument_20_2a_20_3e_249',['ImVector&lt; MyDocument * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20mydocument_20_3e_250',['ImVector&lt; MyDocument &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20sdl_5ffcolor_20_3e_251',['ImVector&lt; SDL_FColor &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20sdl_5fgamecontroller_20_2a_20_3e_252',['ImVector&lt; SDL_GameController * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20sdl_5fgamepad_20_2a_20_3e_253',['ImVector&lt; SDL_Gamepad * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20unsigned_20char_20_3e_254',['ImVector&lt; unsigned char &gt;',['../structImVector.html',1,'']]],
  ['inputtextcallback_5fuserdata_255',['InputTextCallback_UserData',['../structInputTextCallback__UserData.html',1,'']]]
];
