IF(STP_DEB_CALC_DIVISION_RESULT_INSPECT)
    ADD_COMPILE_DEFINITIONS(STP_DEB_CALC_DIVISION_RESULT_INSPECT)
ENDIF()

IF(STP_DEB_CALC_MULTIPLY_RESULT_INSPECT)
    ADD_COMPILE_DEFINITIONS(STP_DEB_CALC_MULTIPLY_RESULT_INSPECT)
ENDIF()

IF(STP_DEB_MATRIX_REF_RESULT_INSPECT)
    ADD_COMPILE_DEFINITIONS(STP_DEB_MATRIX_REF_RESULT_INSPECT)
ENDIF()
