name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi there! Welcome to Steppable. Our devs will soon look into this, in the meantime, thank you very much for spotting that out!"
        pr-message: "Hi there! Welcome to Steppable. Our devs will soon look into this, in the meantime, thank you very much for your improvement suggestion!"
