---
name: Create a Source Distribution
on:
    push:
        branches: ["main", "develop"]
        paths:
            - "**.cpp"
            - "**.hpp"
            - "**.py"
            - "sdist.yml"
    pull_request:
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                cache: 'pip'
                python-version: ${{ matrix.python_version }}

            - name: Install dependencies
              run: pip install .
              shell: bash

            - name: Python Build
              run: python setup.py sdist

            - name: Upload SDist Artifact
              uses: actions/upload-artifact@v4.3.1
              with:
                # Artifact name
                name: sdist
                # A file, directory or wildcard pattern that describes what to upload
                path: ${{ github.workspace }}/dist
